# Generated by Django 5.0.4 on 2024-06-07 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facecheckin', '0003_remove_transaction_datetime_transaction_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='created_at',
            field=models.DateTimeField(verbose_name='Created_at'),
        ),
    ]
